#!/bin/env python

import argparse
import sys
import os
import numpy as np
import matplotlib.pyplot as plt
import pickle

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument( "statfile", help="pickle of stats generated by dump_aggregate_pickle")
    args = parser.parse_args()
    return args

args = parse_args()

stats = pickle.load(open(args.statfile))

blobs = stats.keys()
blobs = sorted(blobs)
blobs = [b for b in blobs if 'act_in_data' in b or 'wgt_data' in b]

for blob in blobs:
    print blob,',',
print ''

for i in range(min(len(stats[blob]['max']),50)):
    for blob in blobs:
        dmax = stats[blob]['max'][i]
        dmin = stats[blob]['min'][i]
        std  = stats[blob]['std'][i]
        absmax = max(abs(dmax),abs(dmin))
        print std,',',
    print ''
